### ISSUE TITLE
ERROR: Integrity check failed.

### ISSUE THREAD

**Issue by elliottd** [srvk/how2-dataset#5]
Hi,

I have tried to download the transcripts using the `install.sh` script but I received an ERROR message. Here is the console output leading up to the script printing the ERROR message.

Do you have any suggestions for what I might be doing wrong here?

> Number of total samples: 2305
> Reading ./translations.pt.bz2 file...
> Traceback (most recent call last):
>   File "scripts/21-extract-pt", line 30, in <module>
>     for line in f:
>   File "/home/lvx122/miniconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
>     return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)
> Number of segments/videos: 2305/175
> Reading .vtt files...
> 100%|########################################| 175/175 [00:00<00:00, 559.45it/s]
> Reading offset file...
> 100%|###################################| 2305/2305 [00:00<00:00, 684596.43it/s]
> 18 multi-sentence segments will be formed manually.
> Dumping segments
> Traceback (most recent call last):
>   File "scripts/20-reconstruct-data", line 110, in <module>
>     of_id.write('{} {}\n'.format(key, content[key]))
> UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 26: ordinal not in range(128)
> 
> Verifying the integrity of final 300h text files
> #########################################
> ~/data/how2-dataset/reproduce/300h ~/data/how2-dataset/reproduce/300h
> ERROR: Integrity check failed. Please create an issue with the /tmp/tmp.66Wwa7N9Ra attached.

> cat /tmp/tmp.66Wwa7N9Ra
> data/dev5/text.en: FAILED
> data/dev5/text.id.en: FAILED
> sha1sum: data/dev5/text.id.pt: No such file or directory
> data/dev5/text.id.pt: FAILED open or read
> sha1sum: data/dev5/text.pt: No such file or directory
> data/dev5/text.pt: FAILED open or read
> data/train/text.en: FAILED
> data/train/text.id.en: FAILED
> sha1sum: data/train/text.id.pt: No such file or directory
> data/train/text.id.pt: FAILED open or read
> sha1sum: data/train/text.pt: No such file or directory
> data/train/text.pt: FAILED open or read
> data/val/text.en: FAILED
> data/val/text.id.en: FAILED
> sha1sum: data/val/text.id.pt: No such file or directory
> data/val/text.id.pt: FAILED open or read
> sha1sum: data/val/text.pt: No such file or directory
> data/val/text.pt: FAILED open or read
> sha1sum: WARNING: 6 listed files could not be read
> sha1sum: WARNING: 6 computed checksums did NOT match

**Comment by ozancaglayan** [comment]
Any news on this?

**Comment by shrutijpalaskar** [comment]
Hi Desmond,

Which stage of the installation pipeline did you get this error? Were you able to finish the VTT download?

**Comment by ozancaglayan** [comment]
We discussed this with Desmond externally and the problem seemed to be related to his UNIX environment and some locale settings.
